# Generated by Django 6.0.5 on 2026-05-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_user_alter_wallet_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='Wallet_id',
            new_name='wallet_id',
        ),
    ]
