# Generated by Django 6.0.5 on 2026-05-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_rename_wallet_id_wallet_wallet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transction_id',
            new_name='transaction_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='refrence_key',
            field=models.CharField(default=4, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
