# Generated by Django 6.0.5 on 2026-05-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_rename_transction_id_transaction_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('refrence_key', 'transaction_type')},
        ),
    ]
