# Generated by Django 6.0.5 on 2026-05-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_transactionlog_delete_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='amount',
            field=models.DecimalField(decimal_places=16, max_digits=32),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=32),
        ),
    ]
